name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  flutter_dotenv: ^6.0.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  cloud_firestore: ^6.0.1
  geolocator: ^14.0.2
  url_launcher: ^6.1.10
  google_generative_ai: ^0.4.0
  image_picker: ^0.8.7+4
  firebase_storage: ^13.0.6
  google_mlkit_image_labeling: ^0.14.0
  google_mlkit_object_detection: ^0.15.0
  intl: ^0.19.0
  http: ^1.2.0
  geocoding: ^3.0.0
  speech_to_text: ^7.0.0
  flutter_tts: ^4.0.2
  permission_handler: ^11.3.0
  firebase_messaging: ^16.0.0
  camera: ^0.11.0+2
  audioplayers: ^6.1.0
  firebase_ai: ^3.8.0
  record: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
